### ISSUE TITLE
import device midi

### ISSUE THREAD

**Issue by CyBerNetX** [Vampouille/superboucle#36]
hi the import of midi instrument (*.sbm file) did not functional
i wanted to import my apc mini but i cant import the sbm file describ in Device Midi post

**Comment by Vampouille** [comment]
Hello,

There is an issue with sbm import tools. I will fix this.

In the meantime, you can try learn feature because you can modify your APC configuration. So an sbm file from one user may not work with another user if they don't have same APC configuration.

You can find detailed instruction here : http://superboucle.nura.eu/index.php/midi-devices/

**Comment by Vampouille** [comment]
Hello, this is the same issue as #30
