### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dvzrv** [Vampouille/superboucle#48]
Is there still something happening with superboucle?
I recently took over the pro-audio section for Arch Linux and would like to package this software in the future.

As this is all python3, do you plan on providing a setuptools based installation?

**Comment by Vampouille** [comment]
> Is there still something happening with superboucle?

I still plan to add support for clip with midi data, but, currently, I have no time to implement this feature :-(

> I recently took over the pro-audio section for Arch Linux and would like to package this software in the future.

good news, it can help to use pad like novation launchpad with linux.

> As this is all python3, do you plan on providing a setuptools based installation?

Yes, I also plan to do it but I have never created such file. So your help is welcome, do you have some links or example that I can follow to provide a setuptools based installation?

**Comment by luzpaz** [comment]
any progress on this ?

**Comment by Vampouille** [comment]
> any progress on this ?

There is some progress ! I'm currently working on the packaging. SuperBoucle is now mentioned in debian database :-)

see the last suggested package https://packages.debian.org/buster/multimedia-looping

I created a branch https://github.com/Vampouille/superboucle/tree/add_setup_py which contains a work in progress version of setup.py. I also have files to create a debian package `/debian/*`(not commited). It currently build a superboucle debian package that I need to test now.

My plan is to provide:
* pypi package
* debian-like package (debian, ubuntu)

**Comment by luzpaz** [comment]
Nice!
@dvzrv are you still involved in the Arch pro-audio ?  
This would be great

**Comment by Vampouille** [comment]
This PR #57 include debian packaging files and a valid setup.py. Any comments are welcome on the packaging.

**Comment by dvzrv** [comment]
@Vampouille excellent. The debian stuff is not at all useful to me, but I'm looking forward to creating a package with the help of setuptools from this!
Please make sure to tag a new version after merging! :)

**Comment by trebmuh** [comment]
@Vampouille nice, the debian packaging rule will definitely be useful on here. Will suggest/PR some improvements on it (already started actually).

**Comment by Vampouille** [comment]
TODO:
* use jack lib from system
* fix timebase master/slave issue

**Comment by dvzrv** [comment]
@Vampouille is there anything blocking a new release?

**Comment by manucontrovento** [comment]
Hi everyone. I uploaded my version, just released, in my repository
I added a bunch of features and fixes.
For the moment, I think I'll proceed eventually with other releases in my repository. I don't know if @Vampouille wants to try it and merge them in master branch? I'd still keep the two branches separated, especially since it's my first python coding experience and it is possible that some code could have been written better than I did.

**Comment by manucontrovento** [comment]
HI @Vampouille 
on suggestion from community, I changed the application name of my fork, since at the moment I think I could only manage a separate development. I hope you won't be upset about this. But I always give credit to your work and to the original application. If in future you'll have the time and you'll want to merge the code we'll work on it
have a nice day!

**Comment by Vampouille** [comment]
Hi @manucontrovento, If plan to maintain a fork for long term it make sense to change the name. 
Can you list the modifications in your fork, I think we can merge some modifications. Based on issues you open, you have good ideas ;-) Unfortunatly, I don't have enough time to develop new features, but if you're merge requests is "mergeable", I will find some times to review and merge your work.

**Comment by Vampouille** [comment]
> @Vampouille wants to try it and merge them in master branch?

yes I want

**Comment by Vampouille** [comment]
I created #83 to keep tracks of modifications made with @manucontrovento.

**Comment by manucontrovento** [comment]
HI @Vampouille  first of all glad to see you again around! 
I'm thinking about what's the better solution. My idea was, at this point, to maintain a separate fork. At first I uploaded my version into my fork, keeping the same name. Then on forums they told me that since my developing was going on a separate way I should have changed the name. That's why I did it. I'm sorry not having waited for you, but I needed changes quickly and had time just now to develop them. I couldn't wait anymore. I also thought that you were too busy and that you wouldn't have the time to test and merge all my code. You also have to consider that I'm learning-by-doing (even if I think that my long experience in C#, .NET etc. is helping me doing the best I can do) so I'm not sure that you'd accept and merge all this coding, changes, etc.
When giving birth to a separate creature, I changed a bit of other things, most of all the namespaces. So, at now you can't just merge my code because it wouldn't work. You'll have a lot of errors. I dind't thought about it because, as I already said, I supposed you wouldn't have time anymore for SB development. Just today I was thinking if change filenames extensions to distinguish them and to furtherly separate the two apps (e.g.  .sbs --> .sts, .sbm --> .stm, or something like that). I thought I could mantain .sbs/.sts extensions just to load old songs, but to save in .sts format only.
So, if you'd like my development to go back in a direction closer to SB and your master branch, I'll change again namespaces, so e.g. my spintool/gui.py will return to be superboucle/gui.py, and the same in all the code as well. It will took me some time but I can do it. I don't know if I explained myself, I could have done a bit of mess.
At the moment, I'm doing other changes to make a further release with other improvements (as I said, I have to do all these things now because in future I'm not sure I'll have the time to).
You also asked me a change list of what I already changed. I copy/paste from my release:

## Features

* Preferences window
* One-shot clip
* Start a clip just after recording it
* Show clip details when triggered
* Show clip details when its volume is changed from MIDI controller
* Preferred grid size (useful to automatically match new songs grid size to your controller's button grid size)
* Choice of recording color (amber is default, red available from now)
* Open playlist and/or scenes window on start up
* Saving windows position
* Added file name in clip description display
* Added master and clip volume amount (0-100) near the knobs
* Added "rec" status near transport info when in recording mode
* Showing console message if missing input JACK ports, on starting
* Light-on all buttons on controller (even scenes buttons and transport buttons)
* Light-off device buttons on application closing
* New clips inherit song beat divider when added
* Including "starting" clips when creating a new scene
* Automatically select a scene when added (not launching it: just to show its details)

## Fixes

* Can't open several instances of scenes and playlist windows anymore
* Fixed cancel file loading error, adding a clip with ctrl+click on cell
* Fixed not-editable-clip name occasional condition
* Fixed occasional unwilling scene start when deleting a clip




Last but not least, I want you to know that in every place I'm writing that I didn't create the main thing and that original SB project is your idea and if not for you we couldn't do all this.

**Comment by manucontrovento** [comment]
ok @Vampouille , I thought about it and I decided to rename again all namespaces, switching to original .../superboucle/*.py , so you could download my master branch and merge whatever you want more easily, I'm about to release new version so I'll do this further change and then I'll upload new version

And file name extensions will remain your SB extensions as well.

In a few time I'll be ready

**Comment by manucontrovento** [comment]
Hi @Vampouille 
you'll have a lot of things to read :)
So, new release is ready and online:

https://github.com/manucontrovento/SpinTool/releases/tag/v20.04.13

For a while I'll keep this running. I have another to-do list but next weeks I'll have to do other things too.  Here's new changelist:


## Features

* New copy/paste clip details function
* Added About window (in Info menu)
* Added menu action to open Online Wiki (in Info menu)
* Added song annotation post-it window
* New keyboard shortcuts using function keys
* On scene manager, a scene scelection updated when triggering a scene by MIDI controller
* On MIDI controller, scene buttons are lighted-up when selected, only if scene exhists
* start scene: when opening a song, if a starting scene exhist, related scene button on controller is lighted-up too

## Fixes

* Fixed UI appearence messing, defining styles for all windows and widgets
* Fixed Add port dialog behaviour (now it's editable without closing Port manager)
* Fixed volume change error message on empty-cell volume changing
* Fixed File not found error message, when canceling and Open song dialog


So, concerning code merging and compatibility: I switched back all namespaces to superboucle. So it will be easier for you to take the code you need. The only file name I dind't restore is boucle.py (I kept spin.py to distinguish better the application). Pay attention to settings too: I didn't use your Qt settings, since I wanted separate settings. So my applications loads and saves settings to different paths

About your issue #83, I started my development from your latest commits (so, I took latest master branch + latest connections fixes from debug branch) so everything should be fine.

About directories, current paths are:
docs
docs/img                for Wiki images
midi_controllers     for .sbm files

I hope not to forget anything.
have a nice day
manu

**Comment by Vampouille** [comment]
@manucontrovento I'm really impressed by the amount of features you add to superboucle :-) Be able to improve opensource software without restrictions is very important. I'm also very happy to see that you keep original filename in code because I want to maintain this project for long term even if I have not enough time now to properly maintain this project. I will find some time to read carefully your modifications. Thanks!

**Comment by manucontrovento** [comment]
@Vampouille thanks for your appreciation, I have a further list of potential features, and other suggestions are coming in my Issues section already.
About original SB, you could start introducing the new changes that you like most, and case by case I could show you where in the code I changed those things

**Comment by manucontrovento** [comment]
Hi everyone. I don't mean to steal focus from SuperBoucle, I just want to tell everybody that meanwhile, together with @sonejostudios  we implemented a huge amount of features in SpinTool, including a "live" mixer with MIDI binding; a completely new management for MIDI devices with also sends, resets of controls, etc; new use cases for the clips ("metronome" clips, always-playing clips, functions to force clips starting despite of bar...); some functions in a "Song" menu to massively edit clips; a Preferences window to customize many behaviours.. etc
we already released many version. I'm about to release a new one, with new Gui, new functions (clone MIDI device, rename scenes..), further MIDI bindings for devices, etc
bye
Manu

**Comment by trebmuh** [comment]
>  I don't mean to steal focus from SuperBoucle

Well, it looks like so. Unless Vampouille agrees.

**Comment by trebmuh** [comment]
>  I don't mean to steal focus from SuperBoucle

Well, it looks like so. Unless @Vampouille agrees.

**Comment by trebmuh** [comment]
>  I don't mean to steal focus from SuperBoucle

Well, it could looks like so. (_Unless @Vampouille agrees, obviously._)

**Comment by sonejostudios** [comment]
Here is the link: https://github.com/manucontrovento/SpinTool

**Comment by manucontrovento** [comment]
> > I don't mean to steal focus from SuperBoucle
> 
> Well, it could looks like so. (_Unless @Vampouille agrees, obviously._)

Hi @trebmuh , I just wrote the news here since Vampouille asked to be up-to-date about ST's releases, since he's interested in merging some features. If not, I can remove the post obviously.
Have a nice day everyone!

**Comment by dvzrv** [comment]
As there is no movement, I'll close this to get rid of an old ticket.
